### ISSUE TITLE
Document possibility of accessing "unauthorized" data

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/search_and_populate_data_from_another_project#14]
This was discussed in 2 long responses that are now unrecoverable because one was verbal and another was lost to a page reload. I need to describe in the README that people can see data in projects they don't have access to but that's actually fine because the admin has to allow it first, preferably more elegantly than just stated so that said admins easily understand what they're doing when configuring.

**Comment by pbchase** [comment]
Addressed by PR #15
