### ISSUE TITLE
Create option to limit search to one field

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/search_and_populate_data_from_another_project#22]
Large projects get increasingly slow to search, the core DataSearch that we are hijacking limits the search space by forcing users to only search within one field in projects larger than 20k records.

Add a new option at the project level to re-enable this functionality. When toggled, we should

1. Stop hiding the field selection box: https://github.com/ctsit/search_and_populate_data_from_another_project/blob/37613f41893742102248199ddf1a9f6e8d22b79b/js/custom_data_search.js#L2-L3
1. Empty its options and replace them with the target fields (i.e. *values* from the `mapping` associated with the current form

**Comment by mbentz-uf** [comment]
Addressed by #23
